# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/finflow_payment?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Babal1111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Razorpay Configuration
razorpay.key.id=rzp_test_Sk0s5FcAaqhzCy
razorpay.key.secret=9lgyWT4CKoCaGRthXmjebfUx
razorpay.amount=500
