# ===== Stage 1: Build =====
FROM node:20-alpine AS build
WORKDIR /app

COPY ./finflow-frontend/package*.json ./
RUN npm install

COPY ./finflow-frontend/ ./
RUN npm run build

# ===== Stage 2: Runtime =====
FROM nginx:alpine
COPY --from=build /app/dist/finflow-frontend/browser /usr/share/nginx/html
COPY ./docker-files/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
